### PR TITLE
Fix errors being thrown

### LINKED ISSUE #98: generate-machines-manifest.js is throwing an error when executing ./generate-machines-manifest.sh
When following GCE docs here [https://wksctl.readthedocs.io/en/latest/wks-on-gce.html](https://wksctl.readthedocs.io/en/latest/wks-on-gce.html) this line is throwing https://github.com/weaveworks/wksctl/blob/1e3e9c1e882572c4473d21cd68ab4a8adf9b8a79/examples/gce/generate-machines-manifest.js#L3

```
./generate-machines-manifest.sh
generate-machines-manifest.js:3
const input = std.param.String("instances", "instances.json");
                        ^
TypeError: Cannot read property 'String' of undefined
    at generate-machines-manifest.js:3:25
```

Here're the changes I used to get past the error: [https://github.com/weaveworks/wksctl/pull/96](https://github.com/weaveworks/wksctl/pull/96)

### PR DESCRIPTION
**Pull request by bobhenkel**
When running `./generate-machines-manifest.sh` I'm seeing this error. This change appears to fix that issue.

```
generate-machines-manifest.js:4
const input = std.param.String("instances", "instances.json");
                        ^
TypeError: Cannot read property 'String' of undefined
    at generate-machines-manifest.js:4:25
```

Fixes #98.

### CODE REVIEW

File: examples/gce/generate-machines-manifest.js [hunk 1]
```diff
@@ -1,4 +1,5 @@
-import std from "@jkcfg/std";
+import * as std from '@jkcfg/std';
+import * as param from '@jkcfg/std/param';
 
 const input = std.param.String("instances", "instances.json");
 const user = std.param.String("user");
```
Comment (fbarl) [inline examples/gce/generate-machines-manifest.js]:
```suggestion
const user = param.String("user");
```

File: examples/gce/generate-machines-manifest.js [hunk 2]
```diff
@@ -1,4 +1,5 @@
-import std from "@jkcfg/std";
+import * as std from '@jkcfg/std';
+import * as param from '@jkcfg/std/param';
 
 const input = std.param.String("instances", "instances.json");
```
Comment (fbarl) [inline examples/gce/generate-machines-manifest.js]:
```suggestion
const input = param.String("instances", "instances.json");
```
